# Generated by Django 4.2.1 on 2023-05-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(default='', max_length=1000)),
                ('response', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
