# Generated by Django 4.2.1 on 2023-05-07 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dummy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='datas',
            table='chat',
        ),
    ]
